/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursemanagement;
/**
 *
 * @author deema
 */

import javax.swing.JOptionPane;
import javax .swing.table.DefaultTableModel;

public class CourseForm extends javax.swing.JFrame {
    
    private CourseManager manager = new CourseManager();
    
    private static final java.util.logging.Logger logger = 
            java.util.logging.Logger.getLogger(CourseForm.class.getName());

    /**
     * Creates new form CourseForm
     */
    public CourseForm() {
        initComponents();
        Helpers.readFile();
        loadCoursesToTable();
    }
    private void loadCoursesToTable() {

    DefaultTableModel model =
            (DefaultTableModel) tblCourses.getModel();

    model.setRowCount(0);

    for (Course course : manager.getAllCourses()) {

        model.addRow(new Object[]{
            course.getCourseId(),
            course.getCourseCode(),
            course.getCourseTitle(),
            course.getCreditHours(),
            course.getDepartment(),
            course.getMaxSeats(),
            course.getLevel(),
            course.getStatus()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCourseID = new javax.swing.JTextField();
        txtCourseCode = new javax.swing.JTextField();
        txtCourseTitle = new javax.swing.JTextField();
        txtCreditHours = new javax.swing.JTextField();
        txtDepartment = new javax.swing.JTextField();
        txtMaxSeats = new javax.swing.JTextField();
        txtLevel = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnViewAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        btnReport = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Course ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Course Code");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Course Title");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Credit Hours");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Department");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Maximum Seats");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Level");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Status");

        txtCourseCode.addActionListener(this::txtCourseCodeActionPerformed);

        txtCourseTitle.addActionListener(this::txtCourseTitleActionPerformed);

        txtDepartment.addActionListener(this::txtDepartmentActionPerformed);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Offered", "Not Offered", "Full" }));

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnViewAll.setText("View All");
        btnViewAll.addActionListener(this::btnViewAllActionPerformed);

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Code", "Course Title", "Credit Hours", "Department", "Max Seats", "Level", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCoursesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCourses);

        btnReport.setText("Report");
        btnReport.addActionListener(this::btnReportActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Course Management System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete)
                            .addComponent(btnClear)
                            .addComponent(btnAdd)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnSearch)
                                                    .addComponent(btnUpdate)
                                                    .addComponent(btnViewAll)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(txtCreditHours, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(btnReport)))
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCourseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(106, 106, 106)))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(582, 582, 582)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(64, 64, 64)
                        .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCourseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCreditHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnUpdate))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearch)
                            .addComponent(btnDelete))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClear)
                            .addComponent(btnViewAll))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReport))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = tblCourses.getSelectedRow();
        int originalCourseId = Integer.parseInt(
        tblCourses.getValueAt(selectedRow, 0).toString()
);
if (selectedRow == -1) {
    JOptionPane.showMessageDialog(
            this,
            "Please select a course from the table."
    );
} else {
    try {
        int id = Integer.parseInt(txtCourseID.getText());
        String code = txtCourseCode.getText();
        String title = txtCourseTitle.getText();
        int creditHours = Integer.parseInt(txtCreditHours.getText());
        String department = txtDepartment.getText();
        int maxSeats = Integer.parseInt(txtMaxSeats.getText());
        int level = Integer.parseInt(txtLevel.getText());
        // Converts the selected ComboBox item into a CourseStatus enum
        CourseStatus status = CourseStatus.fromString(
        cmbStatus.getSelectedItem().toString());
        // Creates the updated Course object
        Course updatedCourse = new Course(id,code,title,creditHours,department, 
                maxSeats,level,status);

        manager.updateCourse(originalCourseId, updatedCourse);
        Helpers.writeFile();

        DefaultTableModel model =
                (DefaultTableModel) tblCourses.getModel();

        model.setValueAt(id, selectedRow, 0);
        model.setValueAt(code, selectedRow, 1);
        model.setValueAt(title, selectedRow, 2);
        model.setValueAt(creditHours, selectedRow, 3);
        model.setValueAt(department, selectedRow, 4);
        model.setValueAt(maxSeats, selectedRow, 5);
        model.setValueAt(level, selectedRow, 6);
        model.setValueAt(status, selectedRow, 7);

        JOptionPane.showMessageDialog(
                this,
                "Course updated successfully!"
        );

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(
                this,
                "Please enter valid numbers."
        );
    }
}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtCourseID.setText("");
        txtCourseCode.setText("");
        txtCourseTitle.setText("");
        txtCreditHours.setText("");
        txtDepartment.setText("");
        txtMaxSeats.setText("");
        txtLevel.setText("");
        cmbStatus.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed
        DefaultTableModel model =(DefaultTableModel) tblCourses.getModel();

model.setRowCount(0);

for (Course course : manager.getAllCourses()) {

    model.addRow(new Object[]{
        course.getCourseId(),course.getCourseCode(),course.getCourseTitle(),
        course.getCreditHours(),course.getDepartment(),course.getMaxSeats(),
        course.getLevel(),course.getStatus()});
}
    }//GEN-LAST:event_btnViewAllActionPerformed

    private void txtCourseTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseTitleActionPerformed

    private void txtCourseCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseCodeActionPerformed

    private void txtDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartmentActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      if (txtCourseID.getText().trim().isEmpty()
        || txtCourseCode.getText().trim().isEmpty()
        || txtCourseTitle.getText().trim().isEmpty()
        || txtCreditHours.getText().trim().isEmpty()
        || txtDepartment.getText().trim().isEmpty()
        || txtMaxSeats.getText().trim().isEmpty()
        || txtLevel.getText().trim().isEmpty()) {

    JOptionPane.showMessageDialog(
            this,
            "Please fill in all fields."
    );

    return;
}
        
        try {

    int id = Integer.parseInt(txtCourseID.getText());
    if (manager.courseIdExists(id)) {

    JOptionPane.showMessageDialog(
            this,
            "Course ID already exists."
    );

    return;
}
    String code = txtCourseCode.getText();
    String title = txtCourseTitle.getText();
    int creditHours = Integer.parseInt(txtCreditHours.getText());
    String department = txtDepartment.getText();
    int maxSeats = Integer.parseInt(txtMaxSeats.getText());
    int level = Integer.parseInt(txtLevel.getText());
    if (id <= 0 || creditHours <= 0 || maxSeats <= 0 || level <= 0) {

    JOptionPane.showMessageDialog(
            this,
            "Course ID, credit hours, maximum seats, and level must be greater than zero."
    );

    return;
}
   // Converts the selected ComboBox item into a CourseStatus enum
CourseStatus status = CourseStatus.fromString(
        cmbStatus.getSelectedItem().toString());
    
    Course course = new Course(id, code, title, creditHours, department, maxSeats, level, status);
    manager.addCourse(course);
    Helpers.writeFile();
    DefaultTableModel model =(DefaultTableModel) tblCourses.getModel();

    model.addRow(new Object[]{
        course.getCourseId(),course.getCourseCode(),course.getCourseTitle(),
        course.getCreditHours(),course.getDepartment(),course.getMaxSeats(),
        course.getLevel(),course.getStatus()});

    
    JOptionPane.showMessageDialog(
            this,"Course added successfully!"
    );

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(
            this,"Please enter valid numbers." );
        }
 
 
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         int selectedRow = tblCourses.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(
                this,
                "Please select a course from the table."
        );
        return;
    }

    int courseId = Integer.parseInt(
            tblCourses.getValueAt(selectedRow, 0).toString()
    );

    boolean deleted = manager.deleteCourse(courseId);

    if (deleted) {
        Helpers.writeFile();

        DefaultTableModel model =
                (DefaultTableModel) tblCourses.getModel();

        model.removeRow(selectedRow);

        JOptionPane.showMessageDialog(
                this,
                "Course deleted successfully!"
        );
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyword = JOptionPane.showInputDialog(
        this,"Enter course ID, code, title, department, or status:");

if (keyword != null && !keyword.trim().isEmpty()) {

    java.util.ArrayList<Course> results = manager.searchCourses(keyword.trim());

    DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
    model.setRowCount(0);
    
    for (Course course : results) {
        model.addRow(new Object[]{
            course.getCourseId(),course.getCourseCode(), course.getCourseTitle(),
            course.getCreditHours(),course.getDepartment(),course.getMaxSeats(),
            course.getLevel(),course.getStatus()});
    }
    if (results.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,"No matching course found.");
    }
}
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
    int totalCourses = manager.getAllCourses().size();
    int offeredCourses = 0;
    int notOfferedCourses = 0;
    int fullCourses = 0;

    for (Course course : manager.getAllCourses()) {
        // Counts courses according to their enum status
     if (course.getStatus() == CourseStatus.OFFERED) {
     offeredCourses++;
  }
     else if (course.getStatus() == CourseStatus.NOT_OFFERED) {
     notOfferedCourses++;
  }
     else if (course.getStatus() == CourseStatus.FULL) {
     fullCourses++;
}
    }

    String departmentReport = "";

    java.util.ArrayList<String> countedDepartments = new java.util.ArrayList<>();

    for (Course course : manager.getAllCourses()) {
        String department = course.getDepartment();

        if (!countedDepartments.contains(department.toLowerCase())) {
            int departmentCount = 0;

            for (Course otherCourse : manager.getAllCourses()) {

                if (otherCourse.getDepartment().equalsIgnoreCase(department)) {
                    departmentCount++;
                }
            }

            departmentReport +="\n" + department + ": " + departmentCount;
            countedDepartments.add(department.toLowerCase());
        }
    }

    String report =
            "Total Courses: " + totalCourses
            + "\nOffered Courses: " + offeredCourses
            + "\nNot Offered Courses: " + notOfferedCourses
            + "\nFull Courses: " + fullCourses
            + "\n\nCourses by Department:"
            + departmentReport;

    JOptionPane.showMessageDialog(
            this,
            report,
            "Course Report",
            JOptionPane.INFORMATION_MESSAGE
    );


    }//GEN-LAST:event_btnReportActionPerformed

    private void tblCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCoursesMouseClicked
        int selectedRow = tblCourses.getSelectedRow();

if (selectedRow != -1) {

    DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
    txtCourseID.setText(model.getValueAt(selectedRow, 0).toString());

    txtCourseCode.setText( model.getValueAt(selectedRow, 1).toString());

    txtCourseTitle.setText(model.getValueAt(selectedRow, 2).toString());

    txtCreditHours.setText(model.getValueAt(selectedRow, 3).toString());

    txtDepartment.setText(model.getValueAt(selectedRow, 4).toString());

    txtMaxSeats.setText(model.getValueAt(selectedRow, 5).toString());

    txtLevel.setText(model.getValueAt(selectedRow, 6).toString());

    cmbStatus.setSelectedItem(model.getValueAt(selectedRow, 7).toString());
}
    }//GEN-LAST:event_tblCoursesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CourseForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewAll;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourses;
    private javax.swing.JTextField txtCourseCode;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseTitle;
    private javax.swing.JTextField txtCreditHours;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtMaxSeats;
    // End of variables declaration//GEN-END:variables
}
