/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package courseregistration;

/**
 *
 * @author engha
 */
import java.util.ArrayList;
import studentmanagement.Student;
import coursemanagement.Course;
public class RegistrationGui extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrationGui.class.getName());

    /**
     * Creates new form RegistrationGui
     */
    private RegistrationManagement manager = new RegistrationManagement();
    private ArrayList<Student> students;
private ArrayList<Course> courses;
    public RegistrationGui() {
 initComponents();
    SemesterBox.removeAllItems();
    SemesterBox.addItem("1");
    SemesterBox.addItem("2");
    SemesterBox.addItem("3");
    SemesterBox.addItem("4");
    SemesterBox.addItem("5");
    SemesterBox.addItem("6");
    SemesterBox.addItem("7");
    SemesterBox.addItem("8");

    
    RegistrationStatusbox.removeAllItems();
    RegistrationStatusbox.addItem("Registered");
    RegistrationStatusbox.addItem("Dropped");
    RegistrationStatusbox.addItem("Completed");
    RegistrationStatusbox.addItem("Failed");

    Helpers.readFile();
    loadTable();
    loadStudents();
    loadCourses();
    }
private void loadTable() {

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();

    model.setRowCount(0);

    for (Registration r : Helpers.registrationList) {

        model.addRow(new Object[]{
            r.getRegistrationId(),
            r.getStudentId(),
            r.getStudentName(),
            r.getCourseId(),
            r.getCourseCode(),
            r.getSemester(),
            r.getRegistrationDate(),
            r.getRegistrationStatus()
        });

    }

}
private void loadStudents() {

    students = studentmanagement.Helpers.readFile();
System.out.println("Students = " + students.size());
    StudentIDbox.removeAllItems();
    StudentNamebox.removeAllItems();

    for (Student s : students) {

        StudentIDbox.addItem(s.getStudentID());
        StudentNamebox.addItem(s.getStudentName());

    }
}
private void loadCourses() {

    coursemanagement.Helpers.readFile();

    courses = coursemanagement.Helpers.courses;

    CourseIDbox.removeAllItems();
    CourseCodeBox.removeAllItems();

    for (Course c : courses) {

        CourseIDbox.addItem(String.valueOf(c.getCourseId()));
        CourseCodeBox.addItem(c.getCourseCode());

    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RegistrationIDlbl = new javax.swing.JLabel();
        RegistrationIDtxt = new javax.swing.JTextField();
        StudentIDlbl = new javax.swing.JLabel();
        StudentNamelbl = new javax.swing.JLabel();
        CourseIDlbl = new javax.swing.JLabel();
        CourseCodelbl = new javax.swing.JLabel();
        Semesterlbl = new javax.swing.JLabel();
        RegistrationDatelbl = new javax.swing.JLabel();
        RegistrationStatuslbl = new javax.swing.JLabel();
        Addbtn = new javax.swing.JButton();
        Searchbtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        Clearbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        StudentIDbox = new javax.swing.JComboBox<>();
        StudentNamebox = new javax.swing.JComboBox<>();
        CourseIDbox = new javax.swing.JComboBox<>();
        SemesterBox = new javax.swing.JComboBox<>();
        RegistrationDatetxt = new javax.swing.JTextField();
        RegistrationStatusbox = new javax.swing.JComboBox<>();
        CourseCodeBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Course Registration System");
        jLabel1.setToolTipText("");

        RegistrationIDlbl.setText("Registration ID");

        RegistrationIDtxt.addActionListener(this::RegistrationIDtxtActionPerformed);

        StudentIDlbl.setText("Student ID");

        StudentNamelbl.setText("Student Name");

        CourseIDlbl.setText("Course ID");

        CourseCodelbl.setText("Course Code");

        Semesterlbl.setText("Semester");

        RegistrationDatelbl.setText("Registration Date");

        RegistrationStatuslbl.setText("Registration Status");

        Addbtn.setText("Add");
        Addbtn.addActionListener(this::AddbtnActionPerformed);

        Searchbtn.setText("Search");
        Searchbtn.addActionListener(this::SearchbtnActionPerformed);

        Updatebtn.setText("Update");
        Updatebtn.addActionListener(this::UpdatebtnActionPerformed);

        Deletebtn.setText("Delete");
        Deletebtn.addActionListener(this::DeletebtnActionPerformed);

        Clearbtn.setText("Clear");
        Clearbtn.addActionListener(this::ClearbtnActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Registration ID", "Student ID", "Student Name", "Course ID", "Course Code", "Semester", "Registration Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        StudentIDbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        StudentIDbox.addActionListener(this::StudentIDboxActionPerformed);

        StudentNamebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        StudentNamebox.addActionListener(this::StudentNameboxActionPerformed);

        CourseIDbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CourseIDbox.addActionListener(this::CourseIDboxActionPerformed);

        SemesterBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SemesterBox.addActionListener(this::SemesterBoxActionPerformed);

        RegistrationStatusbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        RegistrationStatusbox.addActionListener(this::RegistrationStatusboxActionPerformed);

        CourseCodeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CourseCodeBox.addActionListener(this::CourseCodeBoxActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Clearbtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RegistrationStatusbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(StudentNamelbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(StudentNamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(StudentIDlbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(StudentIDbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(RegistrationIDlbl)
                                    .addGap(46, 46, 46)
                                    .addComponent(RegistrationIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CourseIDlbl)
                                            .addComponent(CourseCodelbl)
                                            .addComponent(Semesterlbl))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RegistrationStatuslbl)
                                            .addComponent(RegistrationDatelbl))
                                        .addGap(39, 39, 39)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CourseIDbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SemesterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegistrationDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CourseCodeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(211, 211, 211)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Addbtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Searchbtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Updatebtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Deletebtn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addbtn)
                    .addComponent(RegistrationIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistrationIDlbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Searchbtn)
                    .addComponent(StudentIDbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentIDlbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Updatebtn)
                    .addComponent(StudentNamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentNamelbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deletebtn)
                    .addComponent(CourseIDbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CourseIDlbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clearbtn)
                    .addComponent(CourseCodelbl)
                    .addComponent(CourseCodeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SemesterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Semesterlbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrationDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistrationDatelbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrationStatusbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistrationStatuslbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrationIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrationIDtxtActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        try {

   Registration registration = new Registration(
        RegistrationIDtxt.getText(),
        StudentIDbox.getSelectedItem().toString(),
        StudentNamebox.getSelectedItem().toString(),
        Integer.parseInt(CourseIDbox.getSelectedItem().toString()),
        CourseCodeBox.getSelectedItem().toString(),
        SemesterBox.getSelectedItem().toString(),
        RegistrationDatetxt.getText(),
        RegistrationStatusbox.getSelectedItem().toString());

    if (manager.addRegistration(registration)) {

        Helpers.registrationList.add(registration);
        Helpers.writeFile();
        loadTable();

        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) jTable1.getModel();

        model.addRow(new Object[]{
            registration.getRegistrationId(),
            registration.getStudentId(),
            registration.getStudentName(),
            registration.getCourseId(),
            registration.getCourseCode(),
            registration.getSemester(),
            registration.getRegistrationDate(),
            registration.getRegistrationStatus()
        });

        javax.swing.JOptionPane.showMessageDialog(this,
                "Registration Added Successfully");

    } else {

        javax.swing.JOptionPane.showMessageDialog(this,
                "This Student already registered in this course");

    }

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(this,
            "Please enter valid data");

}
    }//GEN-LAST:event_AddbtnActionPerformed

    private void SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbtnActionPerformed
       String id = RegistrationIDtxt.getText();

Registration registration = manager.searchRegistration(id);

if (registration != null) {

    StudentIDbox.setSelectedItem(registration.getStudentId());
StudentNamebox.setSelectedItem(registration.getStudentName());
CourseIDbox.setSelectedItem(String.valueOf(registration.getCourseId()));
CourseCodeBox.setSelectedItem(registration.getCourseCode());
SemesterBox.setSelectedItem(registration.getSemester());
RegistrationDatetxt.setText(registration.getRegistrationDate());
RegistrationStatusbox.setSelectedItem(registration.getRegistrationStatus());

    javax.swing.JOptionPane.showMessageDialog(this, "Registration Found");

} else {

    javax.swing.JOptionPane.showMessageDialog(this, "Registration Not Found");

}
    }//GEN-LAST:event_SearchbtnActionPerformed

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
    Registration registration = new Registration(
        RegistrationIDtxt.getText(),
        StudentIDbox.getSelectedItem().toString(),
        StudentNamebox.getSelectedItem().toString(),
        Integer.parseInt(CourseIDbox.getSelectedItem().toString()),
        CourseCodeBox.getSelectedItem().toString(),
        SemesterBox.getSelectedItem().toString(),
        RegistrationDatetxt.getText(),
        RegistrationStatusbox.getSelectedItem().toString());

if (manager.updateRegistration(registration)) {

    javax.swing.JOptionPane.showMessageDialog(this, "Updated Successfully");
Helpers.writeFile();
loadTable();
} else {

    javax.swing.JOptionPane.showMessageDialog(this, "Registration Not Found");

}
    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbtnActionPerformed
     RegistrationIDtxt.setText("");
RegistrationDatetxt.setText("");

StudentIDbox.setSelectedIndex(0);
StudentNamebox.setSelectedIndex(0);
CourseIDbox.setSelectedIndex(0);
CourseCodeBox.setSelectedIndex(0);
SemesterBox.setSelectedIndex(0);
RegistrationStatusbox.setSelectedIndex(0);
    }//GEN-LAST:event_ClearbtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
       String id = RegistrationIDtxt.getText();

if (manager.deleteRegistration(id)) {

    javax.swing.JOptionPane.showMessageDialog(this, "Deleted Successfully");
Helpers.writeFile();
loadTable();
} else {

    javax.swing.JOptionPane.showMessageDialog(this, "Registration Not Found");

}
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void StudentIDboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIDboxActionPerformed
       int index = StudentIDbox.getSelectedIndex();

if (index >= 0) {

    Student s = students.get(index);

    StudentNamebox.setSelectedItem(s.getStudentName());

    SemesterBox.setSelectedItem(s.getSemester());

}
    }//GEN-LAST:event_StudentIDboxActionPerformed

    private void RegistrationStatusboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationStatusboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrationStatusboxActionPerformed

    private void StudentNameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentNameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentNameboxActionPerformed

    private void CourseIDboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseIDboxActionPerformed
       int index = CourseIDbox.getSelectedIndex();

if (index >= 0) {

    Course c = courses.get(index);

    CourseCodeBox.setSelectedItem(c.getCourseCode());

}
    }//GEN-LAST:event_CourseIDboxActionPerformed

    private void SemesterBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemesterBoxActionPerformed
      
    }//GEN-LAST:event_SemesterBoxActionPerformed

    private void CourseCodeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseCodeBoxActionPerformed
         int index = CourseCodeBox.getSelectedIndex();

    if (index >= 0) {

        Course c = courses.get(index);

        CourseIDbox.setSelectedItem(String.valueOf(c.getCourseId()));

    }
    }//GEN-LAST:event_CourseCodeBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrationGui().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton Clearbtn;
    private javax.swing.JComboBox<String> CourseCodeBox;
    private javax.swing.JLabel CourseCodelbl;
    private javax.swing.JComboBox<String> CourseIDbox;
    private javax.swing.JLabel CourseIDlbl;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JLabel RegistrationDatelbl;
    private javax.swing.JTextField RegistrationDatetxt;
    private javax.swing.JLabel RegistrationIDlbl;
    private javax.swing.JTextField RegistrationIDtxt;
    private javax.swing.JComboBox<String> RegistrationStatusbox;
    private javax.swing.JLabel RegistrationStatuslbl;
    private javax.swing.JButton Searchbtn;
    private javax.swing.JComboBox<String> SemesterBox;
    private javax.swing.JLabel Semesterlbl;
    private javax.swing.JComboBox<String> StudentIDbox;
    private javax.swing.JLabel StudentIDlbl;
    private javax.swing.JComboBox<String> StudentNamebox;
    private javax.swing.JLabel StudentNamelbl;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
